('Distribuidora de Madera Ecológica, S.A.'),
('Telas y Textiles Elegantes, S.A.'),
('Distribuidora de Telas Modernas, Ltda.'),
('Tapicerías del Sur, S.A. de C.V.'),
('Metales Industriales S.A.'),
('Distribuidora de Componentes Metálicos del Este, Ltda.'),
('Ferretería y Metales S.A.'),
('Accesorios para Muebles S.A.'),
('Distribuidora de Herrajes Fino, Ltda.'),
('Herrajes y Componentes Industriales S.A.'),
('Colchones y Descanso S.A.'),
('Distribuidora de Almohadas Ortopédicas, Ltda.'),
('Fabricante de Colchones de Lujo, S.A.'),
('Decoraciones Elegantes S.A.'),
('Distribuidora de Artículos Decorativos, Ltda.'),
('Artículos de Decoración Modernos, S.A.');

